
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.201.110.228:3366/ltsaas_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: devuser
    password: devuser228
  cloud:
    stream:
      kafka:
        #consumer:
        #  configuration:
        #    "[security.protocol]": SSL
        #    ssl:
        #      key-password: 918918
        #      keystore-location: E:\\ssl\\kafka.server.keystore.jks
        #      keystore-password: 918918
        #      truststore.location: E:\\ssl\\kafka.server.truststore.jks
        #      truststore.password: 918918
        binder:
          zk-nodes: 121.201.110.228:12181
          brokers: 121.201.110.228:19092
    bus.trace.enabled: true  # 开启cloud bus的跟踪

# 关闭敏感端点验证 
management:
  security:
    enabled: false

  

  