
server:
  port: 8030

spring:
  application:
    name: ltsv-member-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://userdb:3306/userdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: devuser
    password: devuser228

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_host:1160/eureka/